// <auto-generated />
using Catalog.Persistence.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Catalog.Persistence.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250321200436_Initialize")]
    partial class Initialize
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Catalog")
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Catalog.Domain.Product", b =>
                {
                    b.Property<int>("IDProduct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDProduct"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IDProduct");

                    b.ToTable("Products", "Catalog");

                    b.HasData(
                        new
                        {
                            IDProduct = 1,
                            Description = "Description for Product 1",
                            Name = "Product 1",
                            Price = 333m
                        },
                        new
                        {
                            IDProduct = 2,
                            Description = "Description for Product 2",
                            Name = "Product 2",
                            Price = 180m
                        },
                        new
                        {
                            IDProduct = 3,
                            Description = "Description for Product 3",
                            Name = "Product 3",
                            Price = 508m
                        },
                        new
                        {
                            IDProduct = 4,
                            Description = "Description for Product 4",
                            Name = "Product 4",
                            Price = 358m
                        },
                        new
                        {
                            IDProduct = 5,
                            Description = "Description for Product 5",
                            Name = "Product 5",
                            Price = 398m
                        },
                        new
                        {
                            IDProduct = 6,
                            Description = "Description for Product 6",
                            Name = "Product 6",
                            Price = 842m
                        },
                        new
                        {
                            IDProduct = 7,
                            Description = "Description for Product 7",
                            Name = "Product 7",
                            Price = 362m
                        },
                        new
                        {
                            IDProduct = 8,
                            Description = "Description for Product 8",
                            Name = "Product 8",
                            Price = 891m
                        },
                        new
                        {
                            IDProduct = 9,
                            Description = "Description for Product 9",
                            Name = "Product 9",
                            Price = 694m
                        },
                        new
                        {
                            IDProduct = 10,
                            Description = "Description for Product 10",
                            Name = "Product 10",
                            Price = 436m
                        },
                        new
                        {
                            IDProduct = 11,
                            Description = "Description for Product 11",
                            Name = "Product 11",
                            Price = 561m
                        },
                        new
                        {
                            IDProduct = 12,
                            Description = "Description for Product 12",
                            Name = "Product 12",
                            Price = 449m
                        },
                        new
                        {
                            IDProduct = 13,
                            Description = "Description for Product 13",
                            Name = "Product 13",
                            Price = 534m
                        },
                        new
                        {
                            IDProduct = 14,
                            Description = "Description for Product 14",
                            Name = "Product 14",
                            Price = 677m
                        },
                        new
                        {
                            IDProduct = 15,
                            Description = "Description for Product 15",
                            Name = "Product 15",
                            Price = 279m
                        },
                        new
                        {
                            IDProduct = 16,
                            Description = "Description for Product 16",
                            Name = "Product 16",
                            Price = 590m
                        },
                        new
                        {
                            IDProduct = 17,
                            Description = "Description for Product 17",
                            Name = "Product 17",
                            Price = 270m
                        },
                        new
                        {
                            IDProduct = 18,
                            Description = "Description for Product 18",
                            Name = "Product 18",
                            Price = 981m
                        },
                        new
                        {
                            IDProduct = 19,
                            Description = "Description for Product 19",
                            Name = "Product 19",
                            Price = 605m
                        },
                        new
                        {
                            IDProduct = 20,
                            Description = "Description for Product 20",
                            Name = "Product 20",
                            Price = 581m
                        },
                        new
                        {
                            IDProduct = 21,
                            Description = "Description for Product 21",
                            Name = "Product 21",
                            Price = 835m
                        },
                        new
                        {
                            IDProduct = 22,
                            Description = "Description for Product 22",
                            Name = "Product 22",
                            Price = 749m
                        },
                        new
                        {
                            IDProduct = 23,
                            Description = "Description for Product 23",
                            Name = "Product 23",
                            Price = 227m
                        },
                        new
                        {
                            IDProduct = 24,
                            Description = "Description for Product 24",
                            Name = "Product 24",
                            Price = 596m
                        },
                        new
                        {
                            IDProduct = 25,
                            Description = "Description for Product 25",
                            Name = "Product 25",
                            Price = 576m
                        },
                        new
                        {
                            IDProduct = 26,
                            Description = "Description for Product 26",
                            Name = "Product 26",
                            Price = 152m
                        },
                        new
                        {
                            IDProduct = 27,
                            Description = "Description for Product 27",
                            Name = "Product 27",
                            Price = 193m
                        },
                        new
                        {
                            IDProduct = 28,
                            Description = "Description for Product 28",
                            Name = "Product 28",
                            Price = 251m
                        },
                        new
                        {
                            IDProduct = 29,
                            Description = "Description for Product 29",
                            Name = "Product 29",
                            Price = 134m
                        },
                        new
                        {
                            IDProduct = 30,
                            Description = "Description for Product 30",
                            Name = "Product 30",
                            Price = 357m
                        },
                        new
                        {
                            IDProduct = 31,
                            Description = "Description for Product 31",
                            Name = "Product 31",
                            Price = 890m
                        },
                        new
                        {
                            IDProduct = 32,
                            Description = "Description for Product 32",
                            Name = "Product 32",
                            Price = 140m
                        },
                        new
                        {
                            IDProduct = 33,
                            Description = "Description for Product 33",
                            Name = "Product 33",
                            Price = 426m
                        },
                        new
                        {
                            IDProduct = 34,
                            Description = "Description for Product 34",
                            Name = "Product 34",
                            Price = 450m
                        },
                        new
                        {
                            IDProduct = 35,
                            Description = "Description for Product 35",
                            Name = "Product 35",
                            Price = 265m
                        },
                        new
                        {
                            IDProduct = 36,
                            Description = "Description for Product 36",
                            Name = "Product 36",
                            Price = 269m
                        },
                        new
                        {
                            IDProduct = 37,
                            Description = "Description for Product 37",
                            Name = "Product 37",
                            Price = 269m
                        },
                        new
                        {
                            IDProduct = 38,
                            Description = "Description for Product 38",
                            Name = "Product 38",
                            Price = 143m
                        },
                        new
                        {
                            IDProduct = 39,
                            Description = "Description for Product 39",
                            Name = "Product 39",
                            Price = 894m
                        },
                        new
                        {
                            IDProduct = 40,
                            Description = "Description for Product 40",
                            Name = "Product 40",
                            Price = 359m
                        },
                        new
                        {
                            IDProduct = 41,
                            Description = "Description for Product 41",
                            Name = "Product 41",
                            Price = 239m
                        },
                        new
                        {
                            IDProduct = 42,
                            Description = "Description for Product 42",
                            Name = "Product 42",
                            Price = 131m
                        },
                        new
                        {
                            IDProduct = 43,
                            Description = "Description for Product 43",
                            Name = "Product 43",
                            Price = 314m
                        },
                        new
                        {
                            IDProduct = 44,
                            Description = "Description for Product 44",
                            Name = "Product 44",
                            Price = 941m
                        },
                        new
                        {
                            IDProduct = 45,
                            Description = "Description for Product 45",
                            Name = "Product 45",
                            Price = 339m
                        },
                        new
                        {
                            IDProduct = 46,
                            Description = "Description for Product 46",
                            Name = "Product 46",
                            Price = 401m
                        },
                        new
                        {
                            IDProduct = 47,
                            Description = "Description for Product 47",
                            Name = "Product 47",
                            Price = 683m
                        },
                        new
                        {
                            IDProduct = 48,
                            Description = "Description for Product 48",
                            Name = "Product 48",
                            Price = 493m
                        },
                        new
                        {
                            IDProduct = 49,
                            Description = "Description for Product 49",
                            Name = "Product 49",
                            Price = 274m
                        },
                        new
                        {
                            IDProduct = 50,
                            Description = "Description for Product 50",
                            Name = "Product 50",
                            Price = 606m
                        },
                        new
                        {
                            IDProduct = 51,
                            Description = "Description for Product 51",
                            Name = "Product 51",
                            Price = 653m
                        },
                        new
                        {
                            IDProduct = 52,
                            Description = "Description for Product 52",
                            Name = "Product 52",
                            Price = 114m
                        },
                        new
                        {
                            IDProduct = 53,
                            Description = "Description for Product 53",
                            Name = "Product 53",
                            Price = 703m
                        },
                        new
                        {
                            IDProduct = 54,
                            Description = "Description for Product 54",
                            Name = "Product 54",
                            Price = 786m
                        },
                        new
                        {
                            IDProduct = 55,
                            Description = "Description for Product 55",
                            Name = "Product 55",
                            Price = 242m
                        },
                        new
                        {
                            IDProduct = 56,
                            Description = "Description for Product 56",
                            Name = "Product 56",
                            Price = 872m
                        },
                        new
                        {
                            IDProduct = 57,
                            Description = "Description for Product 57",
                            Name = "Product 57",
                            Price = 228m
                        },
                        new
                        {
                            IDProduct = 58,
                            Description = "Description for Product 58",
                            Name = "Product 58",
                            Price = 612m
                        },
                        new
                        {
                            IDProduct = 59,
                            Description = "Description for Product 59",
                            Name = "Product 59",
                            Price = 642m
                        },
                        new
                        {
                            IDProduct = 60,
                            Description = "Description for Product 60",
                            Name = "Product 60",
                            Price = 923m
                        },
                        new
                        {
                            IDProduct = 61,
                            Description = "Description for Product 61",
                            Name = "Product 61",
                            Price = 688m
                        },
                        new
                        {
                            IDProduct = 62,
                            Description = "Description for Product 62",
                            Name = "Product 62",
                            Price = 768m
                        },
                        new
                        {
                            IDProduct = 63,
                            Description = "Description for Product 63",
                            Name = "Product 63",
                            Price = 971m
                        },
                        new
                        {
                            IDProduct = 64,
                            Description = "Description for Product 64",
                            Name = "Product 64",
                            Price = 463m
                        },
                        new
                        {
                            IDProduct = 65,
                            Description = "Description for Product 65",
                            Name = "Product 65",
                            Price = 816m
                        },
                        new
                        {
                            IDProduct = 66,
                            Description = "Description for Product 66",
                            Name = "Product 66",
                            Price = 506m
                        },
                        new
                        {
                            IDProduct = 67,
                            Description = "Description for Product 67",
                            Name = "Product 67",
                            Price = 135m
                        },
                        new
                        {
                            IDProduct = 68,
                            Description = "Description for Product 68",
                            Name = "Product 68",
                            Price = 337m
                        },
                        new
                        {
                            IDProduct = 69,
                            Description = "Description for Product 69",
                            Name = "Product 69",
                            Price = 903m
                        },
                        new
                        {
                            IDProduct = 70,
                            Description = "Description for Product 70",
                            Name = "Product 70",
                            Price = 156m
                        },
                        new
                        {
                            IDProduct = 71,
                            Description = "Description for Product 71",
                            Name = "Product 71",
                            Price = 206m
                        },
                        new
                        {
                            IDProduct = 72,
                            Description = "Description for Product 72",
                            Name = "Product 72",
                            Price = 107m
                        },
                        new
                        {
                            IDProduct = 73,
                            Description = "Description for Product 73",
                            Name = "Product 73",
                            Price = 272m
                        },
                        new
                        {
                            IDProduct = 74,
                            Description = "Description for Product 74",
                            Name = "Product 74",
                            Price = 424m
                        },
                        new
                        {
                            IDProduct = 75,
                            Description = "Description for Product 75",
                            Name = "Product 75",
                            Price = 326m
                        },
                        new
                        {
                            IDProduct = 76,
                            Description = "Description for Product 76",
                            Name = "Product 76",
                            Price = 660m
                        },
                        new
                        {
                            IDProduct = 77,
                            Description = "Description for Product 77",
                            Name = "Product 77",
                            Price = 590m
                        },
                        new
                        {
                            IDProduct = 78,
                            Description = "Description for Product 78",
                            Name = "Product 78",
                            Price = 711m
                        },
                        new
                        {
                            IDProduct = 79,
                            Description = "Description for Product 79",
                            Name = "Product 79",
                            Price = 271m
                        },
                        new
                        {
                            IDProduct = 80,
                            Description = "Description for Product 80",
                            Name = "Product 80",
                            Price = 663m
                        },
                        new
                        {
                            IDProduct = 81,
                            Description = "Description for Product 81",
                            Name = "Product 81",
                            Price = 518m
                        },
                        new
                        {
                            IDProduct = 82,
                            Description = "Description for Product 82",
                            Name = "Product 82",
                            Price = 768m
                        },
                        new
                        {
                            IDProduct = 83,
                            Description = "Description for Product 83",
                            Name = "Product 83",
                            Price = 651m
                        },
                        new
                        {
                            IDProduct = 84,
                            Description = "Description for Product 84",
                            Name = "Product 84",
                            Price = 959m
                        },
                        new
                        {
                            IDProduct = 85,
                            Description = "Description for Product 85",
                            Name = "Product 85",
                            Price = 393m
                        },
                        new
                        {
                            IDProduct = 86,
                            Description = "Description for Product 86",
                            Name = "Product 86",
                            Price = 713m
                        },
                        new
                        {
                            IDProduct = 87,
                            Description = "Description for Product 87",
                            Name = "Product 87",
                            Price = 287m
                        },
                        new
                        {
                            IDProduct = 88,
                            Description = "Description for Product 88",
                            Name = "Product 88",
                            Price = 161m
                        },
                        new
                        {
                            IDProduct = 89,
                            Description = "Description for Product 89",
                            Name = "Product 89",
                            Price = 116m
                        },
                        new
                        {
                            IDProduct = 90,
                            Description = "Description for Product 90",
                            Name = "Product 90",
                            Price = 403m
                        },
                        new
                        {
                            IDProduct = 91,
                            Description = "Description for Product 91",
                            Name = "Product 91",
                            Price = 730m
                        },
                        new
                        {
                            IDProduct = 92,
                            Description = "Description for Product 92",
                            Name = "Product 92",
                            Price = 281m
                        },
                        new
                        {
                            IDProduct = 93,
                            Description = "Description for Product 93",
                            Name = "Product 93",
                            Price = 301m
                        },
                        new
                        {
                            IDProduct = 94,
                            Description = "Description for Product 94",
                            Name = "Product 94",
                            Price = 675m
                        },
                        new
                        {
                            IDProduct = 95,
                            Description = "Description for Product 95",
                            Name = "Product 95",
                            Price = 703m
                        },
                        new
                        {
                            IDProduct = 96,
                            Description = "Description for Product 96",
                            Name = "Product 96",
                            Price = 939m
                        },
                        new
                        {
                            IDProduct = 97,
                            Description = "Description for Product 97",
                            Name = "Product 97",
                            Price = 542m
                        },
                        new
                        {
                            IDProduct = 98,
                            Description = "Description for Product 98",
                            Name = "Product 98",
                            Price = 571m
                        },
                        new
                        {
                            IDProduct = 99,
                            Description = "Description for Product 99",
                            Name = "Product 99",
                            Price = 884m
                        },
                        new
                        {
                            IDProduct = 100,
                            Description = "Description for Product 100",
                            Name = "Product 100",
                            Price = 962m
                        });
                });

            modelBuilder.Entity("Catalog.Domain.ProductInStock", b =>
                {
                    b.Property<int>("IDProductInStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDProductInStock"));

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("IDProductInStock");

                    b.HasIndex("ProductID")
                        .IsUnique();

                    b.ToTable("Stocks", "Catalog");

                    b.HasData(
                        new
                        {
                            IDProductInStock = 1,
                            ProductID = 1,
                            Stock = 3
                        },
                        new
                        {
                            IDProductInStock = 2,
                            ProductID = 2,
                            Stock = 14
                        },
                        new
                        {
                            IDProductInStock = 3,
                            ProductID = 3,
                            Stock = 5
                        },
                        new
                        {
                            IDProductInStock = 4,
                            ProductID = 4,
                            Stock = 7
                        },
                        new
                        {
                            IDProductInStock = 5,
                            ProductID = 5,
                            Stock = 3
                        },
                        new
                        {
                            IDProductInStock = 6,
                            ProductID = 6,
                            Stock = 10
                        },
                        new
                        {
                            IDProductInStock = 7,
                            ProductID = 7,
                            Stock = 13
                        },
                        new
                        {
                            IDProductInStock = 8,
                            ProductID = 8,
                            Stock = 11
                        },
                        new
                        {
                            IDProductInStock = 9,
                            ProductID = 9,
                            Stock = 14
                        },
                        new
                        {
                            IDProductInStock = 10,
                            ProductID = 10,
                            Stock = 8
                        },
                        new
                        {
                            IDProductInStock = 11,
                            ProductID = 11,
                            Stock = 16
                        },
                        new
                        {
                            IDProductInStock = 12,
                            ProductID = 12,
                            Stock = 16
                        },
                        new
                        {
                            IDProductInStock = 13,
                            ProductID = 13,
                            Stock = 10
                        },
                        new
                        {
                            IDProductInStock = 14,
                            ProductID = 14,
                            Stock = 7
                        },
                        new
                        {
                            IDProductInStock = 15,
                            ProductID = 15,
                            Stock = 18
                        },
                        new
                        {
                            IDProductInStock = 16,
                            ProductID = 16,
                            Stock = 10
                        },
                        new
                        {
                            IDProductInStock = 17,
                            ProductID = 17,
                            Stock = 4
                        },
                        new
                        {
                            IDProductInStock = 18,
                            ProductID = 18,
                            Stock = 16
                        },
                        new
                        {
                            IDProductInStock = 19,
                            ProductID = 19,
                            Stock = 14
                        },
                        new
                        {
                            IDProductInStock = 20,
                            ProductID = 20,
                            Stock = 16
                        },
                        new
                        {
                            IDProductInStock = 21,
                            ProductID = 21,
                            Stock = 14
                        },
                        new
                        {
                            IDProductInStock = 22,
                            ProductID = 22,
                            Stock = 12
                        },
                        new
                        {
                            IDProductInStock = 23,
                            ProductID = 23,
                            Stock = 13
                        },
                        new
                        {
                            IDProductInStock = 24,
                            ProductID = 24,
                            Stock = 0
                        },
                        new
                        {
                            IDProductInStock = 25,
                            ProductID = 25,
                            Stock = 17
                        },
                        new
                        {
                            IDProductInStock = 26,
                            ProductID = 26,
                            Stock = 5
                        },
                        new
                        {
                            IDProductInStock = 27,
                            ProductID = 27,
                            Stock = 16
                        },
                        new
                        {
                            IDProductInStock = 28,
                            ProductID = 28,
                            Stock = 5
                        },
                        new
                        {
                            IDProductInStock = 29,
                            ProductID = 29,
                            Stock = 14
                        },
                        new
                        {
                            IDProductInStock = 30,
                            ProductID = 30,
                            Stock = 9
                        },
                        new
                        {
                            IDProductInStock = 31,
                            ProductID = 31,
                            Stock = 16
                        },
                        new
                        {
                            IDProductInStock = 32,
                            ProductID = 32,
                            Stock = 8
                        },
                        new
                        {
                            IDProductInStock = 33,
                            ProductID = 33,
                            Stock = 2
                        },
                        new
                        {
                            IDProductInStock = 34,
                            ProductID = 34,
                            Stock = 6
                        },
                        new
                        {
                            IDProductInStock = 35,
                            ProductID = 35,
                            Stock = 2
                        },
                        new
                        {
                            IDProductInStock = 36,
                            ProductID = 36,
                            Stock = 1
                        },
                        new
                        {
                            IDProductInStock = 37,
                            ProductID = 37,
                            Stock = 6
                        },
                        new
                        {
                            IDProductInStock = 38,
                            ProductID = 38,
                            Stock = 10
                        },
                        new
                        {
                            IDProductInStock = 39,
                            ProductID = 39,
                            Stock = 8
                        },
                        new
                        {
                            IDProductInStock = 40,
                            ProductID = 40,
                            Stock = 6
                        },
                        new
                        {
                            IDProductInStock = 41,
                            ProductID = 41,
                            Stock = 12
                        },
                        new
                        {
                            IDProductInStock = 42,
                            ProductID = 42,
                            Stock = 7
                        },
                        new
                        {
                            IDProductInStock = 43,
                            ProductID = 43,
                            Stock = 19
                        },
                        new
                        {
                            IDProductInStock = 44,
                            ProductID = 44,
                            Stock = 0
                        },
                        new
                        {
                            IDProductInStock = 45,
                            ProductID = 45,
                            Stock = 2
                        },
                        new
                        {
                            IDProductInStock = 46,
                            ProductID = 46,
                            Stock = 15
                        },
                        new
                        {
                            IDProductInStock = 47,
                            ProductID = 47,
                            Stock = 11
                        },
                        new
                        {
                            IDProductInStock = 48,
                            ProductID = 48,
                            Stock = 14
                        },
                        new
                        {
                            IDProductInStock = 49,
                            ProductID = 49,
                            Stock = 7
                        },
                        new
                        {
                            IDProductInStock = 50,
                            ProductID = 50,
                            Stock = 5
                        },
                        new
                        {
                            IDProductInStock = 51,
                            ProductID = 51,
                            Stock = 0
                        },
                        new
                        {
                            IDProductInStock = 52,
                            ProductID = 52,
                            Stock = 13
                        },
                        new
                        {
                            IDProductInStock = 53,
                            ProductID = 53,
                            Stock = 7
                        },
                        new
                        {
                            IDProductInStock = 54,
                            ProductID = 54,
                            Stock = 9
                        },
                        new
                        {
                            IDProductInStock = 55,
                            ProductID = 55,
                            Stock = 16
                        },
                        new
                        {
                            IDProductInStock = 56,
                            ProductID = 56,
                            Stock = 4
                        },
                        new
                        {
                            IDProductInStock = 57,
                            ProductID = 57,
                            Stock = 10
                        },
                        new
                        {
                            IDProductInStock = 58,
                            ProductID = 58,
                            Stock = 15
                        },
                        new
                        {
                            IDProductInStock = 59,
                            ProductID = 59,
                            Stock = 6
                        },
                        new
                        {
                            IDProductInStock = 60,
                            ProductID = 60,
                            Stock = 5
                        },
                        new
                        {
                            IDProductInStock = 61,
                            ProductID = 61,
                            Stock = 0
                        },
                        new
                        {
                            IDProductInStock = 62,
                            ProductID = 62,
                            Stock = 6
                        },
                        new
                        {
                            IDProductInStock = 63,
                            ProductID = 63,
                            Stock = 18
                        },
                        new
                        {
                            IDProductInStock = 64,
                            ProductID = 64,
                            Stock = 17
                        },
                        new
                        {
                            IDProductInStock = 65,
                            ProductID = 65,
                            Stock = 2
                        },
                        new
                        {
                            IDProductInStock = 66,
                            ProductID = 66,
                            Stock = 0
                        },
                        new
                        {
                            IDProductInStock = 67,
                            ProductID = 67,
                            Stock = 2
                        },
                        new
                        {
                            IDProductInStock = 68,
                            ProductID = 68,
                            Stock = 10
                        },
                        new
                        {
                            IDProductInStock = 69,
                            ProductID = 69,
                            Stock = 7
                        },
                        new
                        {
                            IDProductInStock = 70,
                            ProductID = 70,
                            Stock = 17
                        },
                        new
                        {
                            IDProductInStock = 71,
                            ProductID = 71,
                            Stock = 9
                        },
                        new
                        {
                            IDProductInStock = 72,
                            ProductID = 72,
                            Stock = 17
                        },
                        new
                        {
                            IDProductInStock = 73,
                            ProductID = 73,
                            Stock = 11
                        },
                        new
                        {
                            IDProductInStock = 74,
                            ProductID = 74,
                            Stock = 8
                        },
                        new
                        {
                            IDProductInStock = 75,
                            ProductID = 75,
                            Stock = 3
                        },
                        new
                        {
                            IDProductInStock = 76,
                            ProductID = 76,
                            Stock = 7
                        },
                        new
                        {
                            IDProductInStock = 77,
                            ProductID = 77,
                            Stock = 1
                        },
                        new
                        {
                            IDProductInStock = 78,
                            ProductID = 78,
                            Stock = 13
                        },
                        new
                        {
                            IDProductInStock = 79,
                            ProductID = 79,
                            Stock = 12
                        },
                        new
                        {
                            IDProductInStock = 80,
                            ProductID = 80,
                            Stock = 5
                        },
                        new
                        {
                            IDProductInStock = 81,
                            ProductID = 81,
                            Stock = 19
                        },
                        new
                        {
                            IDProductInStock = 82,
                            ProductID = 82,
                            Stock = 10
                        },
                        new
                        {
                            IDProductInStock = 83,
                            ProductID = 83,
                            Stock = 7
                        },
                        new
                        {
                            IDProductInStock = 84,
                            ProductID = 84,
                            Stock = 17
                        },
                        new
                        {
                            IDProductInStock = 85,
                            ProductID = 85,
                            Stock = 1
                        },
                        new
                        {
                            IDProductInStock = 86,
                            ProductID = 86,
                            Stock = 7
                        },
                        new
                        {
                            IDProductInStock = 87,
                            ProductID = 87,
                            Stock = 17
                        },
                        new
                        {
                            IDProductInStock = 88,
                            ProductID = 88,
                            Stock = 10
                        },
                        new
                        {
                            IDProductInStock = 89,
                            ProductID = 89,
                            Stock = 8
                        },
                        new
                        {
                            IDProductInStock = 90,
                            ProductID = 90,
                            Stock = 7
                        },
                        new
                        {
                            IDProductInStock = 91,
                            ProductID = 91,
                            Stock = 13
                        },
                        new
                        {
                            IDProductInStock = 92,
                            ProductID = 92,
                            Stock = 18
                        },
                        new
                        {
                            IDProductInStock = 93,
                            ProductID = 93,
                            Stock = 7
                        },
                        new
                        {
                            IDProductInStock = 94,
                            ProductID = 94,
                            Stock = 16
                        },
                        new
                        {
                            IDProductInStock = 95,
                            ProductID = 95,
                            Stock = 0
                        },
                        new
                        {
                            IDProductInStock = 96,
                            ProductID = 96,
                            Stock = 5
                        },
                        new
                        {
                            IDProductInStock = 97,
                            ProductID = 97,
                            Stock = 15
                        },
                        new
                        {
                            IDProductInStock = 98,
                            ProductID = 98,
                            Stock = 1
                        },
                        new
                        {
                            IDProductInStock = 99,
                            ProductID = 99,
                            Stock = 6
                        },
                        new
                        {
                            IDProductInStock = 100,
                            ProductID = 100,
                            Stock = 9
                        });
                });

            modelBuilder.Entity("Catalog.Domain.ProductInStock", b =>
                {
                    b.HasOne("Catalog.Domain.Product", null)
                        .WithOne("Stock")
                        .HasForeignKey("Catalog.Domain.ProductInStock", "ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Catalog.Domain.Product", b =>
                {
                    b.Navigation("Stock")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
